### ISSUE TITLE
Hello, how do you get the intrinsic information of the camera of the R3live-dataset dataset?

### ISSUE THREAD

**Issue by hr2894235132** [APRIL-ZJU/Coco-LIC#2]

**Comment by Jerry-locker** [comment]
The intrinsic information has been provided in [the config yaml of R3LIVE](https://github.com/hku-mars/r3live/blob/master/config/r3live_config.yaml).

**Comment by hr2894235132** [comment]
> The intrinsic information has been provided in [the config yaml of R3LIVE](https://github.com/hku-mars/r3live/blob/master/config/r3live_config.yaml).

Thanks for the reply, it has been successfully run.
