### ISSUE TITLE
trajectory_estimator.cpp - TrajectoryEstimator::Solve - ceres::Solve(options, problem_.get(), &summary) - double free or corruption

### ISSUE THREAD

**Issue by 1194476287** [APRIL-ZJU/Coco-LIC#5]
Thanks for your work! 
An error occurred when run the program with degenerate_seq_00.bag,and in the code “trajectory_estimator.cpp - TrajectoryEstimator::Solve - ceres::Solve(options, problem_.get(), &summary)；”.
How can I resolve this issue?
![2024-05-09 11-04-56 的屏幕截图](https://github.com/APRIL-ZJU/Coco-LIC/assets/56286815/50c91a88-734f-4000-8520-038bbd544d2c)
![2024-05-09 18-23-35 的屏幕截图](https://github.com/APRIL-ZJU/Coco-LIC/assets/56286815/00f1732d-5f89-48e3-b031-e45798b27bd8)
![2024-05-09 18-18-28 的屏幕截图](https://github.com/APRIL-ZJU/Coco-LIC/assets/56286815/ca5da47f-e559-475e-8db3-5637ddcbc6cb)

**Comment by 1194476287** [comment]
![2024-05-09 16-56-23 的屏幕截图](https://github.com/APRIL-ZJU/Coco-LIC/assets/56286815/6eeda582-6c36-41ab-8dec-f787f39fd9cb)
and gdb report this.

**Comment by 1194476287** [comment]
Manually connect the PCL (1.13) library like this
![2024-05-13 11-40-44 的屏幕截图](https://github.com/APRIL-ZJU/Coco-LIC/assets/56286815/50189ea8-7b0a-4921-a208-00d062e15e3d)

**Comment by qlsinori** [comment]
Hello, could you please show the detailed method you used to solve this problem? The image is missing half of the content.
